/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope;

// Take control of all pages as soon as the service worker activates
self.skipWaiting();
clientsClaim();

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Cache Supabase API requests with NetworkFirst strategy
registerRoute(
  /^https:\/\/ixcjeoibvhkdhqitkbat\.supabase\.co\/.*/i,
  new NetworkFirst({
    cacheName: 'supabase-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache Google Fonts with CacheFirst strategy
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Push notification event listener
self.addEventListener('push', (event: PushEvent) => {
  console.log('Push notification received:', event);

  let notificationData = {
    title: 'Finora',
    body: 'Você tem uma nova notificação',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    tag: 'default',
    data: {},
  };

  if (event.data) {
    try {
      const data = event.data.json();
      notificationData = {
        title: data.title || notificationData.title,
        body: data.message || data.body || notificationData.body,
        icon: data.icon || notificationData.icon,
        badge: data.badge || notificationData.badge,
        tag: data.tag || data.type || notificationData.tag,
        data: data.data || data,
      };
    } catch (error) {
      console.error('Error parsing push data:', error);
      notificationData.body = event.data.text();
    }
  }

  const promiseChain = self.registration.showNotification(
    notificationData.title,
    {
      body: notificationData.body,
      icon: notificationData.icon,
      badge: notificationData.badge,
      tag: notificationData.tag,
      data: notificationData.data,
      vibrate: [200, 100, 200],
      requireInteraction: false,
    }
  );

  event.waitUntil(promiseChain);
});

// Notification click event listener
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('Notification clicked:', event);

  event.notification.close();

  // Get the URL to open
  let urlToOpen = '/';

  if (event.notification.data) {
    // Custom navigation based on notification type
    const data = event.notification.data;

    if (data.url) {
      urlToOpen = data.url;
    } else if (data.type === 'cash_low') {
      urlToOpen = '/dashboard?tab=projection';
    } else if (data.type === 'goal_progress') {
      urlToOpen = '/dashboard?tab=goals';
    } else if (data.type === 'analysis_ready') {
      urlToOpen = '/dashboard?tab=analysis';
    } else if (data.goal_id) {
      urlToOpen = `/dashboard?tab=goals&goal=${data.goal_id}`;
    }
  }

  // Navigate to the URL
  const promiseChain = clients.matchAll({
    type: 'window',
    includeUncontrolled: true,
  }).then((windowClients) => {
    // Check if there's already a window open
    for (let i = 0; i < windowClients.length; i++) {
      const client = windowClients[i];
      if (client.url === self.registration.scope + urlToOpen.substring(1) && 'focus' in client) {
        return client.focus();
      }
    }

    // If no window is open, open a new one
    if (clients.openWindow) {
      return clients.openWindow(urlToOpen);
    }
  });

  event.waitUntil(promiseChain);
});

// Notification close event listener
self.addEventListener('notificationclose', (event: NotificationEvent) => {
  console.log('Notification closed:', event);
  // You can track notification dismissals here if needed
});

// Background sync for offline notifications
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'sync-notifications') {
    console.log('Syncing notifications...');
    // Implement background sync logic here if needed
  }
});

// Message event listener for communication with the main thread
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  console.log('Service worker received message:', event.data);

  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }

  // Send back a response
  if (event.ports[0]) {
    event.ports[0].postMessage({ received: true });
  }
});

console.log('Service worker loaded with push notification support');
